# Generated by Django 4.2.3 on 2023-10-07 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_usermodel_profilr_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='profilr_photo',
            new_name='profile_photo',
        ),
    ]
