# Generated by Django 4.2.3 on 2023-10-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_adres'),
    ]

    operations = [
        migrations.AddField(
            model_name='adres',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='adres',
            name='county',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='adres',
            name='district',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='adres',
            name='number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='adres',
            name='street',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
