# Generated by Django 4.2.3 on 2023-10-08 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_adres_city_adres_county_adres_district_adres_number_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='adres',
            new_name='addresses',
        ),
    ]
