# Generated by Django 4.2.3 on 2023-10-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_rename_adres_addresses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addresses',
            options={'verbose_name': 'adresler', 'verbose_name_plural': 'adreslerim'},
        ),
        migrations.AddField(
            model_name='addresses',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
