# Generated by Django 4.2.3 on 2023-10-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_addresses_options_addresses_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='county',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='district',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='number',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='street',
            field=models.TextField(max_length=255),
        ),
    ]
