# Generated by Django 4.2.3 on 2023-10-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_addresses_city_alter_addresses_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='street',
            field=models.CharField(max_length=255),
        ),
    ]
