# Generated by Django 4.2.3 on 2023-09-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopp_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping_model',
            name='image',
            field=models.ImageField(upload_to='image'),
        ),
    ]
