# Generated by Django 4.2.3 on 2023-08-18 15:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopp_app', '0002_mybasket_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping_model',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name=models.TextField()),
        ),
    ]
