# Generated by Django 4.2.3 on 2023-08-31 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopp_app', '0002_usermode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userMode',
        ),
    ]
