# Generated by Django 4.2.3 on 2023-10-01 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopp_app', '0002_alter_shopping_model_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mybasket_model',
            name='product',
        ),
        migrations.RemoveField(
            model_name='myfavorite_model',
            name='product',
        ),
        migrations.AddField(
            model_name='mybasket_model',
            name='myBasket_product',
            field=models.ManyToManyField(to='shopp_app.shopping_model'),
        ),
        migrations.AddField(
            model_name='myfavorite_model',
            name='favorite_product',
            field=models.ManyToManyField(to='shopp_app.shopping_model'),
        ),
        migrations.AlterField(
            model_name='mybasket_model',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='myfavorite_model',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
