# Generated by Django 4.2.3 on 2023-08-31 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopp_app', '0003_delete_usermode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mybasket_model',
            name='user',
        ),
        migrations.RemoveField(
            model_name='myfavorite_model',
            name='user',
        ),
    ]
