# Generated by Django 4.2.3 on 2023-10-01 13:12

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopp_app', '0003_remove_mybasket_model_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mybasket_model',
            name='myBasket_product',
        ),
        migrations.RemoveField(
            model_name='myfavorite_model',
            name='favorite_product',
        ),
        migrations.AddField(
            model_name='mybasket_model',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopp_app.shopping_model'),
        ),
        migrations.AddField(
            model_name='myfavorite_model',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopp_app.shopping_model'),
        ),
        migrations.AlterField(
            model_name='shopping_model',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
