# Generated by Django 4.2.3 on 2023-08-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopp_app', '0003_alter_shopping_model_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping_model',
            name='content',
            field=models.TextField(),
        ),
    ]
