# Generated by Django 4.2.3 on 2023-08-20 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopp_app', '0004_alter_shopping_model_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='myFavorite_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopp_app.shopping_model')),
            ],
        ),
    ]
