# Generated by Django 4.2.3 on 2023-10-01 13:20

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopp_app', '0005_alter_mybasket_model_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybasket_model',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='myfavorite_model',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shopping_model',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name=models.TextField()),
        ),
    ]
