# Generated by Django 4.2.3 on 2023-10-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopp_app', '0006_alter_mybasket_model_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mybasket_model',
            name='product',
        ),
        migrations.RemoveField(
            model_name='myfavorite_model',
            name='product',
        ),
        migrations.AddField(
            model_name='mybasket_model',
            name='product',
            field=models.ManyToManyField(to='shopp_app.shopping_model'),
        ),
        migrations.AddField(
            model_name='myfavorite_model',
            name='product',
            field=models.ManyToManyField(to='shopp_app.shopping_model'),
        ),
    ]
