# Generated by Django 4.2.3 on 2023-10-15 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopp_app', '0007_remove_mybasket_model_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mybasket_model',
            name='product',
        ),
        migrations.RemoveField(
            model_name='myfavorite_model',
            name='product',
        ),
        migrations.AddField(
            model_name='mybasket_model',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopp_app.shopping_model'),
        ),
        migrations.AddField(
            model_name='myfavorite_model',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopp_app.shopping_model'),
        ),
    ]
